ding:
  description: 发送消息到钉钉机器人。
  fields:
    message:
      description: 消息内容。
      example: '您好，我是钉钉机器人'

miai:
  description: 用小爱音箱播报消息。
  fields:
    message:
      description: 消息内容
      example: '音量50%，我是小爱'
