- alias: 主卧空调调节
  initial_state: false
  trigger:
    - platform: time
      at: '20:30:01'
    - platform: state
      entity_id: sensor.zhu_wo_wen_du
  condition:
    - condition: time
      after: '20:00'
      before: '07:20'
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.zhu_wo_wen_du
        sensor_values: [27.5, 29.3, 30, 31, 32]
        alt_sensor_values: [28, 29.5, 30, 31, 32]
        #alt_sensor_values: [28.5, 29.5, 30, 31, 32]
        alt_time_range: [2, 8]
        entity_id: climate.zhu_wo_kong_diao
        entity_attr: fan_mode
        entity_values: [一档, 二档, 三档, 四档, 五档]

- alias: 儿童房空调调节
  initial_state: false
  trigger:
    - platform: time
      at: '20:00:01'
    - platform: state
      entity_id: sensor.er_tong_fang_wen_du
  condition:
    - condition: time
      after: '20:00'
      before: '07:20'
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.er_tong_fang_wen_du
        sensor_values: [22, 22.5, 23, 24, 25]
        alt_sensor_values: [23.3, 24, 25, 26, 27]
        alt_time_range: [2, 8]
        entity_id: climate.er_tong_fang_kong_diao
        entity_attr: fan_mode
        entity_values: [一档, 二档, 三档, 四档, 五档]
        delay: 0

- alias: 书房空调调节
  initial_state: false
  trigger:
    - platform: time
      at: '20:30:01'
    - platform: state
      entity_id: sensor.shu_fang_wen_du
  condition:
    - condition: time
      after: '20:30'
      before: '07:20'
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.shu_fang_wen_du
        #sensor_values: [28, 28.5, 32, 34] #feng_shan_wen_du
        #alt_sensor_values: [28.8, 30, 32, 34]
        sensor_values: [29.7, 30.5, 32, 33]
        alt_sensor_values: [30.5, 31, 32, 33]
        alt_time_range: [2, 8]
        entity_id: climate.shu_fang_kong_diao
        entity_attr: fan_mode
        entity_values: [low, mid, high, highest]
        delay: 0

- alias: 书房风扇调节
  initial_state: false
  trigger:
    - platform: time
      at: '20:30:01'
    - platform: state
      entity_id: sensor.shu_fang_wen_du
  condition:
    - condition: time
      after: '20:30'
      before: '07:20'
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.shu_fang_wen_du
        #sensor_values: [24, 27.5, 30, 32] #feng_shan_wen_du
        #alt_sensor_values: [25, 28.5, 32, 34]
        sensor_values: [26, 28.5, 32, 33]
        alt_sensor_values: [27, 30, 32, 34]
        alt_time_range: [2, 8]
        entity_id: fan.shu_fang_feng_shan
        entity_attr: speed_level
        #service: set_speed
        service_attr: speed
        entity_values: [Level 1, Level 2, Level 3, Level 4]
        delay: 0

- alias: 儿童房风扇调节
  initial_state: false
  trigger:
    - platform: time
      at: '20:00:01'
    - platform: state
      entity_id: sensor.er_tong_fang_wen_du
  condition:
    - condition: time
      after: '20:00'
      before: '07:20'
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.er_tong_fang_wen_du
        sensor_values: [19, 21.2, 24, 25]
        alt_sensor_values: [20, 23, 25, 26]
        alt_time_range: [2, 8]
        entity_id: fan.er_tong_fang_feng_shan
        entity_attr: speed_level
        #service: set_speed
        service_attr: speed
        entity_values: [Level 1, Level 2, Level 3, Level 4]
        delay: 0
